#!/bin/sh

LOGFILE="/home/nlantau/.config/scripts/update.log"

{ sudo pacman -Syuw --noconfirm >/dev/null 2>&1 && echo "> Script ran: `date '+%x %X'`" >> $LOGFILE ;} ||
  echo "Could not run archupdate `date '+%x %X'`" >> $LOGFILE
