#!/bin/sh
# nlantau, 2021-05-09
# Log every minute the computer is on. New logfile every day.

path="/home/nlantau/.config/scripts/log_data"
filename="$(date '+%x').log"
full_path="$path/$filename"

[[ -f $full_path ]] || touch $full_path

date '+%X' >> $full_path
