#!/bin/sh
# nlantau, 2021-05-14

# Count all logged minutes

colors="/home/nlantau/.config/scripts/colors"

[[ -f $colors ]] && source $colors

# Path, days, first logging date
path="${XDG_CONFIG_HOME:-/home/nlantau/.config}/scripts/log_data"
days=$((`ls $path | wc -l`-1))
first_log=$(ls -lt $path | tail -n 1 | grep -Eo '[0-9-]+.log')

# Todays stats
today=$(ls -l $path | tail -n1 | grep -Eo '[0-9-]+.log')
tmin=$(cat $path/$today | wc -l)
first_date=${first_log::-4}

# Sum all logged minutes
for f in $path/*.log; do sum=$((sum + $(cat $f | wc -l))); done

# Print stats
printf "\n$green >$nc ${yellow}Total time since${nc} $first_date ($days days ago): \n\n"
printf "$green >$nc In minutes : $sum\n"
printf "$green >$nc In hours   : " ; bc <<< "scale=2;$sum/60"
printf "$green >$nc In days    : " ; bc <<< "scale=2;$sum/60/24"
echo -e "\n------------------------------\n"
printf "$green >$nc Average/day: \n\n"
printf "$green >$nc In minutes : " ; bc <<< "scale=2;$sum/$days"
printf "$green >$nc In hours   : " ; bc <<< "scale=2;$sum/$days/60"
printf "$green >$nc Percentage : " ; bc <<< "scale=1;$sum/$days/60/24*100"
echo -e "\n------------------------------\n"
printf "$green >$nc ${red}Today${nc}: \n\n"
printf "$green >$nc In minutes : " ; echo $tmin
printf "$green >$nc In hours   : " ; bc <<< "scale=2;$tmin/60"
printf "\n\n"
