#!/bin/sh
# nlantau, 2021-05-14

# Count all logged minutes

path="${XDG_CONFIG_HOME:-/home/nlantau/.config}/scripts/log_data"
days=$((`ls $path | wc -l`-1))
first_log=$(ls -lt $path | tail -n 1 | grep -Eo '[0-9-]+.log')
today=$(ls -l $path | tail -n1 | grep -Eo '[0-9-]+.log')
tmin=$(cat $path/$today | wc -l)
first_date=${first_log::-4}

for f in $path/*.log; do sum=$((sum + $(cat $f | wc -l))); done

printf "\n > Totalt time since $first_date ($days days ago): \n\n"
printf " > In minutes : $sum\n"
printf " > In hours   : " ; echo "scale=2;$sum/60" | bc
printf " > In days    : " ; echo "scale=2;$sum/60/24" | bc
echo -e "\n------------------------------\n"
printf " > Average/day: \n\n"
printf " > In minutes : " ; echo "scale=2;$sum/$days" | bc
printf " > In hours   : " ; echo "scale=2;$sum/$days/60" | bc
printf " > Percentage : " ; echo "scale=1;$sum/$days/60/24*100" | bc
echo -e "\n------------------------------\n"
printf " > Today: \n\n"
printf " > In minutes : " ; echo $tmin
printf " > In hours   : " ; echo "scale=2;$tmin/60" | bc
printf "\n\n"
