#!/bin/sh
# nlantau, 2021-04-24


function setting_laptop {
  xrandr --output \
    eDP1 --mode 1920x1080 --output \
    DP3 --off --output DP1 --off >/dev/null 2>&1
    [[ $? -eq 0 ]] || notify-send "Laptop error"
}

function setting_dual { 
  xrandr --output \
    eDP1 --off --output \
    DP3 --mode 1920x1080 --output \
    DP1 --mode 1920x1080 --right-of DP3 >/dev/null 2>&1
    [[ $? -eq 0 ]] || notify-send "Not Connected"
}

function setting_triple {  
  xrandr --output \
    eDP1 --mode 1920x1080 --output \
    DP3 --mode 1920x1080 --right-of \
    eDP1 --output \
    DP1 --mode 1920x1080 --right-of DP3 >/dev/null 2>&1
    [[ $? -eq 0 ]] || notify-send "Not Connected"
}

function set_xset {
  xset r rate 300 50 || notify-send "xset rate error"
  xset b off || notify-send "xset bell error"
  setxkbmap se || notify-send "Setting SE error"
}



case "$1" in
  "laptop")
    setting_laptop ;
    set_xset ;
    ;;
  "dual")
    setting_dual ;
    set_xset ;
    ;;
  "triple")
    setting_triple ;
    set_xset ;
    ;;
  *)
    notify-send "Multi Monitor Error";;
esac


