#!/usr/bin/bash


case "$1" in
  "laptop") xrandr --output eDP1 --mode 1920x1080 --output DP3 --off --output DP1 --off ;;
  "dual") xrandr --output eDP1 --off --output DP3 --mode 1920x1080 --output DP1 --mode 1920x1080 --right-of DP3 ;;
  *) notify-send "Multi Monitor Error";;
esac
